version: '3.7'

services:
  converter:
    container_name: converter
    build: ./converter
    command: python src/main.py -i ./pascal_voc_dataset -o ./keras_image_dataset
    volumes:
      - ./pascal_voc_dataset:/app/pascal_voc_dataset
      - keras_image_dataset:/app/keras_image_dataset
    env_file: .env

  efficientnet_training:
    container_name: efficientnet_training
    build: ./efficientnet_training
    command: python ./src/main.py -dp /keras_image_dataset -mep /model_export -fe 70 -ufe 40
    volumes:
      - keras_image_dataset:/app/keras_image_dataset
      - ./model_export/effnet:/app/model_export
      - ./logfiles/effnet:/app/logfiles
    env_file: .env
    depends_on:
      converter:
        condition: service_completed_successfully

  efficientdet_training:
    container_name: efficientdet_training
    build: ./efficientdet_training
    command: /bin/bash /app/src/run.sh
    volumes:
      - ./efficientdet_training/src/models/my_efficientdet_d0_coco17_tpu-32:/app/src/models/my_efficientdet_d0_coco17_tpu-32
      - ./model_export/effdet:/app/src/model_export
      - ./pascal_voc_dataset:/app/pascal_voc_dataset
      - ./logfiles/effdet:/app/logfiles
    env_file: .env
    depends_on:
      efficientnet_training:
        condition: service_completed_successfully


    
volumes:
  keras_image_dataset:
