version: '3.7'

services:
  efficientdet_training:
    container_name: efficientdet_training
    build: ./efficientdet_training
    command: /bin/bash /app/src/run.sh
    volumes:
      - ./efficientdet_training/src/annotations:/app/src/annotations
      - ./efficientdet_training/src/models/my_efficientdet_d0_coco17_tpu-32:/app/src/models/my_efficientdet_d0_coco17_tpu-32
      - ./efficientdet_training/src/exported-models:/app/src/exported-models
    env_file: .env