version: '3'

services:
  efficientnet_training:
    container_name: efficientnet_training
    # image: andrewrutherfoord/efficientnet_training:latest
    build: ./efficientnet_training
    command: python ./src/main.py -pvdp /pascal_voc_dataset -kidp /keras_image_dataset -mep /model_export
    volumes:
      - ./pascal_voc_dataset:/app/pascal_voc_dataset
      - keras_image_dataset:/app/keras_image_dataset
      - ./model_export/effnet:/app/model_export
      - ./logfiles/effnet:/app/logfiles
      - ./common_utils:/app/src/utils
    env_file: .env

  efficientdet_training:
    container_name: efficientdet_training
    # image: andrewrutherfoord/efficientdet_training:latest
    build: ./efficientdet_training
    command: /bin/bash /app/src/run.sh
    volumes:
      - ./efficientdet_training/src/models/my_efficientdet_d0_coco17_tpu-32:/app/src/models/my_efficientdet_d0_coco17_tpu-32
      - ./model_export/effdet:/app/src/model_export
      - ./pascal_voc_dataset:/app/pascal_voc_dataset
      - ./logfiles/effdet:/app/logfiles
      - ./common_utils:/app/src/scripts/utils
    env_file: .env
    depends_on:
      efficientnet_training:
        condition: service_completed_successfully
    
volumes:
  keras_image_dataset:
