version: '3.7'

services:
  app:
    container_name: nn-trainer
    build: ./nn_trainer
    command: python ./src/main.py -dp /imageDataset -mep /modelOutput
    volumes:
      - imageDataset:/app/imageDataset
      - ./modelOutput:/app/modelOutput
    env_file: .env
    depends_on:
      converter:
        condition: service_completed_successfully
        
  converter:
    build: ./converter
    command: python src/main.py -i ./pascalVOCInput -o ./imageDataset
    volumes:
      - ./pascalVOCInput:/app/pascalVOCInput
      - imageDataset:/app/imageDataset
    env_file: .env
    
volumes:
  imageDataset:
  